[package]
name = "membercrate3"
version = "0.1.0"
authors = ["LKatalin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
